# Generated by Django 5.0.2 on 2024-02-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issuing_organization',
            field=models.CharField(max_length=50, verbose_name='Issuing Organization'),
        ),
    ]
