# Generated by Django 5.0.2 on 2024-02-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiration_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10, null=True, verbose_name='Expiration Month'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10, null=True, verbose_name='Issue Month'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10, null=True, verbose_name='End Month'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10, null=True, verbose_name='Start Month'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10, null=True, verbose_name='End Month'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10, null=True, verbose_name='Start Month'),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('elementary', 'Elementary proficiency'), ('limited', 'Limited working proficiency'), ('professional', 'Professional working proficiency'), ('full', 'Full professional proficiency'), ('native', 'Native or bilingual proficiency')], max_length=20, verbose_name='Proficiency'),
        ),
    ]
