# Generated by Django 5.0.2 on 2024-02-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_alter_certificate_credential_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='background_image',
        ),
    ]
