# Generated by Django 5.0.2 on 2024-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_alter_certificate_expiration_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='avatars/', width_field='width'),
        ),
    ]
