# Generated by Django 5.0.2 on 2024-02-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
