# Generated by Django 5.0.2 on 2024-02-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_user_facebook_user_github_user_linkedin_user_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(null=True, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='background/'),
        ),
    ]
