# Generated by Django 5.0.2 on 2024-02-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_alter_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Interests'),
        ),
    ]
